// Auto-converted from emojis.js
const LABELS: Record<string, string> = {
    // Smileys & Emotion
    'grinning face': '😀',
    'grinning face with big eyes': '😃',
    'grinning face with smiling eyes': '😄',
    'beaming face with smiling eyes': '😁',
    'grinning squinting face': '😆',
    'grinning face with sweat': '😅',
    'rolling on the floor laughing': '🤣',
    'face with tears of joy': '😂',
    'slightly smiling face': '🙂',
    'upside-down face': '🙃',
    'melting face': '🫠',
    'winking face': '😉',
    'smiling face with smiling eyes': '😊',
    'smiling face with halo': '😇',
    'smiling face with hearts': '🥰',
    'smiling face with heart-eyes': '😍',
    'star-struck': '🤩',
    'face blowing a kiss': '😘',
    'kissing face': '😗',
    'smiling face': '☺',
    'kissing face with closed eyes': '😚',
    'kissing face with smiling eyes': '😙',
    'smiling face with tear': '🥲',
    'face savoring food': '😋',
    'face with tongue': '😛',
    'winking face with tongue': '😜',
    'zany face': '🤪',
    'squinting face with tongue': '😝',
    'money-mouth face': '🤑',
    'smiling face with open hands': '🤗',
    'face with hand over mouth': '🤭',
    'face with open eyes and hand over mouth': '🫢',
    'face with peeking eye': '🫣',
    'shushing face': '🤫',
    'thinking face': '🤔',
    'saluting face': '🫡',
    'zipper-mouth face': '🤐',
    'face with raised eyebrow': '🤨',
    'neutral face': '😐',
    'expressionless face': '😑',
    'face without mouth': '😶',
    'dotted line face': '🫥',
    'face in clouds': '😶‍🌫️',
    'smirking face': '😏',
    'unamused face': '😒',
    'face with rolling eyes': '🙄',
    'grimacing face': '😬',
    'face exhaling': '😮‍💨',
    'lying face': '🤥',
    'shaking face': '🫨',
    'head shaking horizontally': '🙂‍↔️',
    'head shaking vertically': '🙂‍↕️',
    'relieved face': '😌',
    'pensive face': '😔',
    'sleepy face': '😪',
    'drooling face': '🤤',
    'sleeping face': '😴',
    'face with bags under eyes': '🫩',
    'face with medical mask': '😷',
    'face with thermometer': '🤒',
    'face with head-bandage': '🤕',
    'nauseated face': '🤢',
    'face vomiting': '🤮',
    'sneezing face': '🤧',
    'hot face': '🥵',
    'cold face': '🥶',
    'woozy face': '🥴',
    'face with crossed-out eyes': '😵',
    'face with spiral eyes': '😵‍💫',
    'exploding head': '🤯',
    'cowboy hat face': '🤠',
    'partying face': '🥳',
    'disguised face': '🥸',
    'smiling face with sunglasses': '😎',
    'nerd face': '🤓',
    'face with monocle': '🧐',
    'confused face': '😕',
    'face with diagonal mouth': '🫤',
    'worried face': '😟',
    'slightly frowning face': '🙁',
    'frowning face': '☹',
    'face with open mouth': '😮',
    'hushed face': '😯',
    'astonished face': '😲',
    'flushed face': '😳',
    'distorted face': '🫪',
    'pleading face': '🥺',
    'face holding back tears': '🥹',
    'frowning face with open mouth': '😦',
    'anguished face': '😧',
    'fearful face': '😨',
    'anxious face with sweat': '😰',
    'sad but relieved face': '😥',
    'crying face': '😢',
    'loudly crying face': '😭',
    'face screaming in fear': '😱',
    'confounded face': '😖',
    'persevering face': '😣',
    'disappointed face': '😞',
    'downcast face with sweat': '😓',
    'weary face': '😩',
    'tired face': '😫',
    'yawning face': '🥱',
    'face with steam from nose': '😤',
    'enraged face': '😡',
    'angry face': '😠',
    'face with symbols on mouth': '🤬',
    'smiling face with horns': '😈',
    'angry face with horns': '👿',
    'skull': '💀',
    'skull and crossbones': '☠',
    'pile of poo': '💩',
    'clown face': '🤡',
    'ogre': '👹',
    'goblin': '👺',
    'ghost': '👻',
    'alien': '👽',
    'alien monster': '👾',
    'robot': '🤖',
    'grinning cat': '😺',
    'grinning cat with smiling eyes': '😸',
    'cat with tears of joy': '😹',
    'smiling cat with heart-eyes': '😻',
    'cat with wry smile': '😼',
    'kissing cat': '😽',
    'weary cat': '🙀',
    'crying cat': '😿',
    'pouting cat': '😾',
    'see-no-evil monkey': '🙈',
    'hear-no-evil monkey': '🙉',
    'speak-no-evil monkey': '🙊',

    // Hearts & symbols
    'love letter': '💌',
    'heart with arrow': '💘',
    'heart with ribbon': '💝',
    'sparkling heart': '💖',
    'growing heart': '💗',
    'beating heart': '💓',
    'revolving hearts': '💞',
    'two hearts': '💕',
    'heart decoration': '💟',
    'heart exclamation': '❣',
    'broken heart': '💔',
    'heart on fire': '❤️‍🔥',
    'mending heart': '❤️‍🩹',
    'red heart': '❤',
    'pink heart': '🩷',
    'orange heart': '🧡',
    'yellow heart': '💛',
    'green heart': '💚',
    'blue heart': '💙',
    'light blue heart': '🩵',
    'purple heart': '💜',
    'brown heart': '🤎',
    'black heart': '🖤',
    'grey heart': '🩶',
    'white heart': '🤍',
    'kiss mark': '💋',
    'hundred points': '💯',
    'anger symbol': '💢',
    'fight cloud': '🫯',
    'collision': '💥',
    'dizzy': '💫',
    'sweat droplets': '💦',
    'dashing away': '💨',
    'hole': '🕳',
    'speech balloon': '💬',
    'eye in speech bubble': '👁️‍🗨️',
    'left speech bubble': '🗨',
    'right anger bubble': '🗯',
    'thought balloon': '💭',
    'ZZZ': '💤',

    // Hands & body
    'waving hand': '👋',
    'raised back of hand': '🤚',
    'hand with fingers splayed': '🖐',
    'raised hand': '✋',
    'vulcan salute': '🖖',
    'rightwards hand': '🫱',
    'leftwards hand': '🫲',
    'palm down hand': '🫳',
    'palm up hand': '🫴',
    'leftwards pushing hand': '🫷',
    'rightwards pushing hand': '🫸',
    'OK hand': '👌',
    'pinched fingers': '🤌',
    'pinching hand': '🤏',
    'victory hand': '✌',
    'crossed fingers': '🤞',
    'hand with index finger and thumb crossed': '🫰',
    'love-you gesture': '🤟',
    'sign of the horns': '🤘',
    'call me hand': '🤙',
    'backhand index pointing left': '👈',
    'backhand index pointing right': '👉',
    'backhand index pointing up': '👆',
    'middle finger': '🖕',
    'backhand index pointing down': '👇',
    'index pointing up': '☝',
    'index pointing at the viewer': '🫵',
    'thumbs up': '👍',
    'thumbs down': '👎',
    'raised fist': '✊',
    'oncoming fist': '👊',
    'left-facing fist': '🤛',
    'right-facing fist': '🤜',
    'clapping hands': '👏',
    'raising hands': '🙌',
    'heart hands': '🫶',
    'open hands': '👐',
    'palms up together': '🤲',
    'handshake': '🤝',
    'folded hands': '🙏',
    'writing hand': '✍',
    'nail polish': '💅',
    'selfie': '🤳',
    'flexed biceps': '💪',
    'mechanical arm': '🦾',
    'mechanical leg': '🦿',
    'leg': '🦵',
    'foot': '🦶',
    'ear': '👂',
    'ear with hearing aid': '🦻',
    'nose': '👃',
    'brain': '🧠',
    'anatomical heart': '🫀',
    'lungs': '🫁',
    'tooth': '🦷',
    'bone': '🦴',
    'eyes': '👀',
    'eye': '👁',
    'tongue': '👅',
    'mouth': '👄',
    'biting lip': '🫦',

    // People
    'baby': '👶',
    'child': '🧒',
    'boy': '👦',
    'girl': '👧',
    'person': '🧑',
    'person blond hair': '👱',
    'man': '👨',
    'person beard': '🧔',
    'man beard': '🧔‍♂️',
    'woman beard': '🧔‍♀️',
    'man red hair': '👨‍🦰',
    'man curly hair': '👨‍🦱',
    'man white hair': '👨‍🦳',
    'man bald': '👨‍🦲',
    'woman': '👩',
    'woman red hair': '👩‍🦰',
    'person red hair': '🧑‍🦰',
    'woman curly hair': '👩‍🦱',
    'person curly hair': '🧑‍🦱',
    'woman white hair': '👩‍🦳',
    'person white hair': '🧑‍🦳',
    'woman bald': '👩‍🦲',
    'person bald': '🧑‍🦲',
    'woman blond hair': '👱‍♀️',
    'man blond hair': '👱‍♂️',
    'older person': '🧓',
    'old man': '👴',
    'old woman': '👵',
    'person frowning': '🙍',
    'man frowning': '🙍‍♂️',
    'woman frowning': '🙍‍♀️',
    'person pouting': '🙎',
    'man pouting': '🙎‍♂️',
    'woman pouting': '🙎‍♀️',
    'person gesturing NO': '🙅',
    'man gesturing NO': '🙅‍♂️',
    'woman gesturing NO': '🙅‍♀️',
    'person gesturing OK': '🙆',
    'man gesturing OK': '🙆‍♂️',
    'woman gesturing OK': '🙆‍♀️',
    'person tipping hand': '💁',
    'man tipping hand': '💁‍♂️',
    'woman tipping hand': '💁‍♀️',
    'person raising hand': '🙋',
    'man raising hand': '🙋‍♂️',
    'woman raising hand': '🙋‍♀️',
    'deaf person': '🧏',
    'deaf man': '🧏‍♂️',
    'deaf woman': '🧏‍♀️',
    'person bowing': '🙇',
    'man bowing': '🙇‍♂️',
    'woman bowing': '🙇‍♀️',
    'person facepalming': '🤦',
    'man facepalming': '🤦‍♂️',
    'woman facepalming': '🤦‍♀️',
    'person shrugging': '🤷',
    'man shrugging': '🤷‍♂️',
    'woman shrugging': '🤷‍♀️',

    // Roles
    'health worker': '🧑‍⚕️',
    'man health worker': '👨‍⚕️',
    'woman health worker': '👩‍⚕️',
    'student': '🧑‍🎓',
    'man student': '👨‍🎓',
    'woman student': '👩‍🎓',
    'teacher': '🧑‍🏫',
    'man teacher': '👨‍🏫',
    'woman teacher': '👩‍🏫',
    'judge': '🧑‍⚖️',
    'man judge': '👨‍⚖️',
    'woman judge': '👩‍⚖️',
    'farmer': '🧑‍🌾',
    'man farmer': '👨‍🌾',
    'woman farmer': '👩‍🌾',
    'cook': '🧑‍🍳',
    'man cook': '👨‍🍳',
    'woman cook': '👩‍🍳',
    'mechanic': '🧑‍🔧',
    'man mechanic': '👨‍🔧',
    'woman mechanic': '👩‍🔧',
    'factory worker': '🧑‍🏭',
    'man factory worker': '👨‍🏭',
    'woman factory worker': '👩‍🏭',
    'office worker': '🧑‍💼',
    'man office worker': '👨‍💼',
    'woman office worker': '👩‍💼',
    'scientist': '🧑‍🔬',
    'man scientist': '👨‍🔬',
    'woman scientist': '👩‍🔬',
    'technologist': '🧑‍💻',
    'man technologist': '👨‍💻',
    'woman technologist': '👩‍💻',
    'singer': '🧑‍🎤',
    'man singer': '👨‍🎤',
    'woman singer': '👩‍🎤',
    'artist': '🧑‍🎨',
    'man artist': '👨‍🎨',
    'woman artist': '👩‍🎨',
    'pilot': '🧑‍✈️',
    'man pilot': '👨‍✈️',
    'woman pilot': '👩‍✈️',
    'astronaut': '🧑‍🚀',
    'man astronaut': '👨‍🚀',
    'woman astronaut': '👩‍🚀',
    'firefighter': '🧑‍🚒',
    'man firefighter': '👨‍🚒',
    'woman firefighter': '👩‍🚒',
    'police officer': '👮',
    'man police officer': '👮‍♂️',
    'woman police officer': '👮‍♀️',
    'detective': '🕵',
    'man detective': '🕵️‍♂️',
    'woman detective': '🕵️‍♀️',
    'guard': '💂',
    'man guard': '💂‍♂️',
    'woman guard': '💂‍♀️',
    'ninja': '🥷',
    'construction worker': '👷',
    'man construction worker': '👷‍♂️',
    'woman construction worker': '👷‍♀️',
    'person with crown': '🫅',
    'prince': '🤴',
    'princess': '👸',
    'person wearing turban': '👳',
    'man wearing turban': '👳‍♂️',
    'woman wearing turban': '👳‍♀️',
    'person with skullcap': '👲',
    'woman with headscarf': '🧕',
    'person in tuxedo': '🤵',
    'man in tuxedo': '🤵‍♂️',
    'woman in tuxedo': '🤵‍♀️',
    'person with veil': '👰',
    'man with veil': '👰‍♂️',
    'woman with veil': '👰‍♀️',
    'pregnant woman': '🤰',
    'pregnant man': '🫃',
    'pregnant person': '🫄',
    'breast-feeding': '🤱',
    'woman feeding baby': '👩‍🍼',
    'man feeding baby': '👨‍🍼',
    'person feeding baby': '🧑‍🍼',
    'baby angel': '👼',
    'Santa Claus': '🎅',
    'Mrs Claus': '🤶',
    'Mx Claus': '🧑‍🎄',
    'superhero': '🦸',
    'man superhero': '🦸‍♂️',
    'woman superhero': '🦸‍♀️',
    'supervillain': '🦹',
    'man supervillain': '🦹‍♂️',
    'woman supervillain': '🦹‍♀️',
    'mage': '🧙',
    'man mage': '🧙‍♂️',
    'woman mage': '🧙‍♀️',
    'fairy': '🧚',
    'man fairy': '🧚‍♂️',
    'woman fairy': '🧚‍♀️',
    'vampire': '🧛',
    'man vampire': '🧛‍♂️',
    'woman vampire': '🧛‍♀️',
    'merperson': '🧜',
    'merman': '🧜‍♂️',
    'mermaid': '🧜‍♀️',
    'elf': '🧝',
    'man elf': '🧝‍♂️',
    'woman elf': '🧝‍♀️',
    'genie': '🧞',
    'man genie': '🧞‍♂️',
    'woman genie': '🧞‍♀️',
    'zombie': '🧟',
    'man zombie': '🧟‍♂️',
    'woman zombie': '🧟‍♀️',
    'troll': '🧌',

    // Activity
    'person getting massage': '💆',
    'man getting massage': '💆‍♂️',
    'woman getting massage': '💆‍♀️',
    'person getting haircut': '💇',
    'man getting haircut': '💇‍♂️',
    'woman getting haircut': '💇‍♀️',
    'person walking': '🚶',
    'man walking': '🚶‍♂️',
    'woman walking': '🚶‍♀️',
    'person walking facing right': '🚶‍➡️',
    'man walking facing right': '🚶‍♂️‍➡️',
    'woman walking facing right': '🚶‍♀️‍➡️',
    'person standing': '🧍',
    'man standing': '🧍‍♂️',
    'woman standing': '🧍‍♀️',
    'person kneeling': '🧎',
    'man kneeling': '🧎‍♂️',
    'woman kneeling': '🧎‍♀️',
    'person kneeling facing right': '🧎‍➡️',
    'man kneeling facing right': '🧎‍♂️‍➡️',
    'woman kneeling facing right': '🧎‍♀️‍➡️',
    'person with white cane': '🧑‍🦯',
    'man with white cane': '👨‍🦯',
    'woman with white cane': '👩‍🦯',
    'person in motorized wheelchair': '🧑‍🦼',
    'man in motorized wheelchair': '👨‍🦼',
    'woman in motorized wheelchair': '👩‍🦼',
    'person in manual wheelchair': '🧑‍🦽',
    'man in manual wheelchair': '👨‍🦽',
    'woman in manual wheelchair': '👩‍🦽',
    'person running': '🏃',
    'man running': '🏃‍♂️',
    'woman running': '🏃‍♀️',
    'person in steamy room': '🧖',
    'person climbing': '🧗',
    'person golfing': '🏌',
    'horse racing': '🏇',
    'skier': '⛷',
    'snowboarder': '🏂',
    'parachute': '🪂',
    'person lifting weights': '🏋',
    'people wrestling': '🤼',
    'person cartwheeling': '🤸',
    'person bouncing ball': '⛹',
    'person fencing': '🤺',
    'person swimming': '🏊',
    'person biking': '🚴',
    'trophy': '🏆',
    '1st place medal': '🥇',
    '2nd place medal': '🥈',
    '3rd place medal': '🥉',
    'sports medal': '🏅',
    'military medal': '🎖',
    'rosette': '🏵',
    'reminder ribbon': '🎗',
    'ticket': '🎫',
    'admission tickets': '🎟',
    'circus tent': '🎪',
    'person juggling': '🤹',
    'performing arts': '🎭',
    'ballet shoes': '🩰',
    'artist palette': '🎨',
    'clapper board': '🎬',
    'microphone': '🎤',
    'headphone': '🎧',
    'musical score': '🎼',
    'musical keyboard': '🎹',
    'drum': '🥁',
    'long drum': '🪘',
    'saxophone': '🎷',
    'trumpet': '🎺',
    'accordion': '🪗',
    'guitar': '🎸',
    'banjo': '🪕',
    'violin': '🎻',
    'flute': '🪈',
    'game die': '🎲',
    'chess pawn': '♟',
    'bullseye': '🎯',
    'bowling': '🎳',
    'video game': '🎮',
    'slot machine': '🎰',
    'puzzle piece': '🧩',

    // Nature
    'beans': '🫘',
    'cactus': '🌵',
    'christmas tree': '🎄',
    'evergreen tree': '🌲',
    'deciduous tree': '🌳',
    'palm tree': '🌴',
    'wood': '🪵',
    'seedling': '🌱',
    'herb': '🌿',
    'shamrock': '☘',
    'four leaf clover': '🍀',
    'pine decoration': '🎍',
    'potted plant': '🪴',
    'tanabata tree': '🎋',
    'leaf fluttering in wind': '🍃',
    'fallen leaf': '🍂',
    'maple leaf': '🍁',
    'nest with eggs': '🪺',
    'empty nest': '🪹',
    'mushroom': '🍄',
    'spiral shell': '🐚',
    'coral': '🪸',
    'rock': '🪨',
    'sheaf of rice': '🌾',
    'bouquet': '💐',
    'tulip': '🌷',
    'rose': '🌹',
    'wilted flower': '🥀',
    'lotus': '🪷',
    'hibiscus': '🌺',
    'cherry blossom': '🌸',
    'blossom': '🌼',
    'sunflower': '🌻',
    'sun with face': '🌞',
    'full moon with face': '🌝',
    'first quarter moon with face': '🌛',
    'last quarter moon with face': '🌜',
    'new moon with face': '🌚',
    'full moon': '🌕',
    'waning gibbous moon': '🌖',
    'last quarter moon': '🌗',
    'waning crescent moon': '🌘',
    'new moon': '🌑',
    'waxing crescent moon': '🌒',
    'first quarter moon': '🌓',
    'waxing gibbous moon': '🌔',
    'crescent moon': '🌙',
    'glowing star': '🌟',
    'star': '⭐',
    'shooting star': '🌠',
    'milky way': '🌌',
    'sun': '☀',
    'sun behind small cloud': '🌤',
    'sun behind cloud': '⛅',
    'sun behind large cloud': '🌥',
    'cloud': '☁',
    'sun behind rain cloud': '🌦',
    'cloud with rain': '🌧',
    'cloud with lightning and rain': '⛈',
    'cloud with lightning': '🌩',
    'cloud with snow': '🌨',
    'snowflake': '❄',
    'snowman': '☃',
    'snowman without snow': '⛄',
    'wind face': '🌬',
    'droplet': '💧',
    'bubbles': '🫧',
    'umbrella with rain drops': '☔',
    'umbrella': '☂',
    'water wave': '🌊',
    'fog': '🌫',
    'cyclone': '🌀',
    'rainbow': '🌈',
    'high voltage': '⚡',
    'fire': '🔥',
    'tornado': '🌪',
    'thermometer': '🌡',
    'comet': '☄',

    // Travel & places
    'snow-capped mountain': '🏔',
    'mountain': '⛰',
    'volcano': '🌋',
    'mount fuji': '🗻',
    'camping': '🏕',
    'beach with umbrella': '🏖',
    'desert': '🏜',
    'desert island': '🏝',
    'national park': '🏞',
    'stadium': '🏟',
    'classical building': '🏛',
    'building construction': '🏗',
    'brick': '🧱',
    'hut': '🛖',
    'houses': '🏘',
    'derelict house': '🏚',
    'house': '🏠',
    'house with garden': '🏡',
    'office building': '🏢',
    'japanese post office': '🏣',
    'post office': '🏤',
    'hospital': '🏥',
    'bank': '🏦',
    'hotel': '🏨',
    'love hotel': '🏩',
    'convenience store': '🏪',
    'school': '🏫',
    'department store': '🏬',
    'factory': '🏭',
    'japanese castle': '🏯',
    'castle': '🏰',
    'wedding': '💒',
    'tokyo tower': '🗼',
    'statue of liberty': '🗽',
    'church': '⛪',
    'mosque': '🕌',
    'hindu temple': '🛕',
    'synagogue': '🕍',
    'shinto shrine': '⛩',
    'kaaba': '🕋',
    'fountain': '⛲',
    'tent': '⛺',
    'foggy': '🌁',
    'night with stars': '🌃',
    'cityscape': '🏙',
    'sunrise over mountains': '🌄',
    'sunrise': '🌅',
    'cityscape at dusk': '🌆',
    'sunset': '🌇',
    'bridge at night': '🌉',
    'hot springs': '♨',
    'carousel horse': '🎠',
    'playground slide': '🛝',
    'ferris wheel': '🎡',
    'roller coaster': '🎢',
    'barber pole': '💈',

    // Vehicles
    'locomotive': '🚂',
    'railway car': '🚃',
    'high-speed train': '🚄',
    'bullet train': '🚅',
    'train': '🚆',
    'metro': '🚇',
    'light rail': '🚈',
    'station': '🚉',
    'tram': '🚊',
    'monorail': '🚝',
    'mountain railway': '🚞',
    'tram car': '🚋',
    'bus': '🚌',
    'oncoming bus': '🚍',
    'trolleybus': '🚎',
    'minibus': '🚐',
    'ambulance': '🚑',
    'fire engine': '🚒',
    'police car': '🚓',
    'oncoming police car': '🚔',
    'taxi': '🚕',
    'oncoming taxi': '🚖',
    'automobile': '🚗',
    'oncoming automobile': '🚘',
    'sport utility vehicle': '🚙',
    'pickup truck': '🛻',
    'delivery truck': '🚚',
    'articulated lorry': '🚛',
    'tractor': '🚜',
    'racing car': '🏎',
    'motorcycle': '🏍',
    'motor scooter': '🛵',
    'manual wheelchair': '🦽',
    'motorized wheelchair': '🦼',
    'auto rickshaw': '🛺',
    'bicycle': '🚲',
    'kick scooter': '🛴',
    'skateboard': '🛹',
    'roller skate': '🛼',
    'bus stop': '🚏',
    'motorway': '🛣',
    'railway track': '🛤',
    'oil drum': '🛢',
    'fuel pump': '⛽',
    'wheel': '🛞',
    'police car light': '🚨',
    'horizontal traffic light': '🚥',
    'vertical traffic light': '🚦',
    'stop sign': '🛑',
    'construction': '🚧',
    'anchor': '⚓',
    'ring buoy': '🛟',
    'sailboat': '⛵',
    'canoe': '🛶',
    'speedboat': '🚤',
    'passenger ship': '🛳',
    'ferry': '⛴',
    'motor boat': '🛥',
    'ship': '🚢',
    'airplane': '✈',
    'small airplane': '🛩',
    'airplane departure': '🛫',
    'airplane arrival': '🛬',
    'seat': '💺',
    'helicopter': '🚁',
    'suspension railway': '🚟',
    'mountain cableway': '🚠',
    'aerial tramway': '🚡',
    'satellite': '🛰',
    'rocket': '🚀',
    'flying saucer': '🛸',
    'bellhop bell': '🛎',
    'luggage': '🧳',

    // Clocks
    'hourglass done': '⌛',
    'hourglass not done': '⏳',
    'watch': '⌚',
    'alarm clock': '⏰',
    'stopwatch': '⏱',
    'timer clock': '⏲',
    'mantelpiece clock': '🕰',
    'twelve o clock': '🕛',
    'twelve-thirty': '🕧',
    'one o clock': '🕐',
    'one-thirty': '🕜',
    'two o clock': '🕑',
    'two-thirty': '🕝',
    'three o clock': '🕒',
    'three-thirty': '🕞',
    'four o clock': '🕓',
    'four-thirty': '🕟',
    'five o clock': '🕔',
    'five-thirty': '🕠',
    'six o clock': '🕕',
    'six-thirty': '🕡',
    'seven o clock': '🕖',
    'seven-thirty': '🕢',
    'eight o clock': '🕗',
    'eight-thirty': '🕣',
    'nine o clock': '🕘',
    'nine-thirty': '🕤',
    'ten o clock': '🕙',
    'ten-thirty': '🕥',
    'eleven o clock': '🕚',
    'eleven-thirty': '🕦',
    'ringed planet': '🪐',
    'sparkles': '✨',

    // Food
    'green apple': '🍏',
    'red apple': '🍎',
    'tangerine': '🍊',
    'lemon': '🍋',
    'banana': '🍌',
    'watermelon': '🍉',
    'grapes': '🍇',
    'strawberry': '🍓',
    'blueberries': '🫐',
    'melon': '🍈',
    'cherries': '🍒',
    'peach': '🍑',
    'mango': '🥭',
    'pineapple': '🍍',
    'coconut': '🥥',
    'kiwi fruit': '🥝',
    'tomato': '🍅',
    'eggplant': '🍆',
    'avocado': '🥑',
    'broccoli': '🥦',
    'leafy green': '🥬',
    'cucumber': '🥒',
    'hot pepper': '🌶',
    'bell pepper': '🫑',
    'carrot': '🥕',
    'garlic': '🧄',
    'onion': '🧅',
    'potato': '🥔',
    'roasted sweet potato': '🍠',
    'ginger root': '🫚',
    'croissant': '🥐',
    'bagel': '🥯',
    'bread': '🍞',
    'baguette bread': '🥖',
    'pretzel': '🥨',
    'cheese wedge': '🧀',
    'egg': '🥚',
    'cooking': '🍳',
    'butter': '🧈',
    'pancakes': '🥞',
    'waffle': '🧇',
    'bacon': '🥓',
    'cut of meat': '🥩',
    'poultry leg': '🍗',
    'meat on bone': '🍖',
    'hot dog': '🌭',
    'hamburger': '🍔',
    'french fries': '🍟',
    'pizza': '🍕',
    'flatbread': '🫓',
    'sandwich': '🥪',
    'stuffed flatbread': '🥙',
    'falafel': '🧆',
    'taco': '🌮',
    'burrito': '🌯',
    'tamale': '🫔',
    'green salad': '🥗',
    'shallow pan of food': '🥘',
    'fondue': '🫕',
    'canned food': '🥫',
    'spaghetti': '🍝',
    'steaming bowl': '🍜',
    'pot of food': '🍲',
    'curry rice': '🍛',
    'sushi': '🍣',
    'bento box': '🍱',
    'dumpling': '🥟',
    'oyster': '🦪',
    'fried shrimp': '🍤',
    'rice ball': '🍙',
    'cooked rice': '🍚',
    'rice cracker': '🍘',
    'fish cake with swirl': '🍥',
    'moon cake': '🥮',
    'oden': '🍢',
    'cupcake': '🧁',
    'shortcake': '🍰',
    'birthday cake': '🎂',
    'custard': '🍮',
    'lollipop': '🍭',
    'candy': '🍬',
    'chocolate bar': '🍫',
    'popcorn': '🍿',
    'doughnut': '🍩',
    'cookie': '🍪',
    'chestnut': '🌰',
    'peanuts': '🥜',
    'honey pot': '🍯',
    'beverage box': '🧃',
    'cup with straw': '🥤',
    'bubble tea': '🧋',
    'teapot': '🫖',
    'teacup without handle': '🍵',
    'hot beverage': '☕',
    'pouring liquid': '🫗',
    'beer mug': '🍺',
    'clinking beer mugs': '🍻',
    'clinking glasses': '🥂',
    'wine glass': '🍷',
    'jar': '🫙',
    'cocktail glass': '🍸',
    'tropical drink': '🍹',
    'mate': '🧉',
    'bottle with popping cork': '🍾',
    'ice': '🧊',
    'spoon': '🥄',
    'fork and knife': '🍴',
    'fork and knife with plate': '🍽',
    'chopsticks': '🥢',
    'salt': '🧂',

    // Sports / games
    'soccer ball': '⚽',
    'baseball': '⚾',
    'softball': '🥎',
    'basketball': '🏀',
    'volleyball': '🏐',
    'american football': '🏈',
    'rugby football': '🏉',
    'tennis': '🎾',
    'flying disc': '🥏',
    'cricket game': '🏏',
    'field hockey': '🏑',
    'ice hockey': '🏒',
    'lacrosse': '🥍',
    'ping pong': '🏓',
    'badminton': '🏸',
    'boxing glove': '🥊',
    'martial arts uniform': '🥋',
    'goal net': '🥅',
    'flag in hole': '⛳',
    'fishing pole': '🎣',
    'diving mask': '🤿',
    'running shirt': '🎽',
    'skis': '🎿',
    'sled': '🛷',
    'curling stone': '🥌',
    'yo-yo': '🪀',
    'kite': '🪁',
    'pool 8 ball': '🎱',
    'crystal ball': '🔮',
    'magic wand': '🪄',
    'nazar amulet': '🧿',
    'hamsa': '🪬',
    'joystick': '🕹',
    'piñata': '🪅',
    'nesting dolls': '🪆',
    'spade suit': '♠',
    'heart suit': '♥',
    'diamond suit': '♦',
    'club suit': '♣',
    'joker': '🃏',
    'mahjong red dragon': '🀄',
    'flower playing cards': '🎴',
    'framed picture': '🖼',
    'thread': '🧵',
    'sewing needle': '🪡',
    'yarn': '🧶',
    'knot': '🪢',

    // Clothing
    'glasses': '👓',
    'sunglasses': '🕶',
    'goggles': '🥽',
    'safety vest': '🦺',
    'necktie': '👔',
    't-shirt': '👕',
    'jeans': '👖',
    'scarf': '🧣',
    'gloves': '🧤',
    'coat': '🧥',
    'socks': '🧦',
    'dress': '👗',
    'kimono': '👘',
    'sari': '🥻',
    'one-piece swimsuit': '🩱',
    'briefs': '🩲',
    'shorts': '🩳',
    'bikini': '👙',
    'womans clothes': '👚',
    'folding hand fan': '🪭',
    'purse': '👛',
    'handbag': '👜',
    'clutch bag': '👝',
    'backpack': '🎒',
    'womans hat': '👒',
    'top hat': '🎩',
    'billed cap': '🧢',
    'military helmet': '🪖',
    'rescue worker helmet': '⛑',
    'prayer beads': '📿',
    'lipstick': '💄',
    'ring': '💍',
    'gem stone': '💎',

    // Sound & objects
    'muted speaker': '🔇',
    'speaker low volume': '🔈',
    'speaker medium volume': '🔉',
    'speaker high volume': '🔊',
    'loudspeaker': '📢',
    'megaphone': '📣',
    'postal horn': '📯',
    'bell': '🔔',
    'bell with slash': '🔕',
    'musical note': '🎵',
    'musical notes': '🎶',
    'studio microphone': '🎙',
    'level slider': '🎚',
    'control knobs': '🎛',
    'radio': '📻',
    'mobile phone': '📱',
    'mobile phone with arrow': '📲',
    'telephone': '☎',
    'telephone receiver': '📞',
    'pager': '📟',
    'fax machine': '📠',
    'battery': '🔋',
    'low battery': '🪫',
    'electric plug': '🔌',
    'laptop': '💻',
    'desktop computer': '🖥',
    'printer': '🖨',
    'keyboard': '⌨',
    'computer mouse': '🖱',
    'trackball': '🖲',
    'computer disk': '💽',
    'floppy disk': '💾',
    'optical disk': '💿',
    'dvd': '📀',
    'abacus': '🧮',
    'movie camera': '🎥',
    'film frames': '🎞',
    'film projector': '📽',
    'television': '📺',
    'camera': '📷',
    'camera with flash': '📸',
    'video camera': '📹',
    'videocassette': '📼',
    'magnifying glass tilted left': '🔍',
    'magnifying glass tilted right': '🔎',
    'candle': '🕯',
    'light bulb': '💡',
    'flashlight': '🔦',
    'red paper lantern': '🏮',
    'diya lamp': '🪔',
    'notebook with decorative cover': '📔',
    'closed book': '📕',
    'open book': '📖',
    'green book': '📗',
    'blue book': '📘',
    'orange book': '📙',
    'books': '📚',
    'notebook': '📓',
    'ledger': '📒',
    'page with curl': '📃',
    'scroll': '📜',
    'page facing up': '📄',
    'newspaper': '📰',
    'rolled-up newspaper': '🗞',
    'bookmark tabs': '📑',
    'bookmark': '🔖',
    'label': '🏷',
    'coin': '🪙',
    'money bag': '💰',
    'yen banknote': '💴',
    'dollar banknote': '💵',
    'euro banknote': '💶',
    'pound banknote': '💷',
    'money with wings': '💸',
    'credit card': '💳',
    'receipt': '🧾',
    'chart increasing with yen': '💹',
    'envelope': '✉',
    'e-mail': '📧',
    'incoming envelope': '📨',
    'envelope with arrow': '📩',
    'outbox tray': '📤',
    'inbox tray': '📥',
    'package': '📦',
    'closed mailbox with raised flag': '📫',
    'closed mailbox with lowered flag': '📪',
    'open mailbox with raised flag': '📬',
    'open mailbox with lowered flag': '📭',
    'postbox': '📮',
    'ballot box with ballot': '🗳',
    'pencil': '✏',
    'black nib': '✒',
    'fountain pen': '🖋',
    'pen': '🖊',
    'memo': '📝',
    'briefcase': '💼',
    'file folder': '📁',
    'open file folder': '📂',
    'card index dividers': '🗂',
    'calendar': '📅',
    'tear-off calendar': '📆',
    'spiral notepad': '🗒',
    'spiral calendar': '🗓',
    'card index': '📇',
    'chart increasing': '📈',
    'chart decreasing': '📉',
    'bar chart': '📊',
    'clipboard': '📋',
    'pushpin': '📌',
    'round pushpin': '📍',
    'world map': '🗺',
    'paperclip': '📎',
    'linked paperclips': '🖇',
    'straight ruler': '📏',
    'triangular ruler': '📐',
    'scissors': '✂',
    'card file box': '🗃',
    'file cabinet': '🗄',
    'wastebasket': '🗑',
    'locked': '🔒',
    'unlocked': '🔓',
    'locked with pen': '🔏',
    'locked with key': '🔐',
    'key': '🔑',
    'old key': '🗝',
    'hammer': '🔨',
    'axe': '🪓',
    'pick': '⛏',
    'hammer and pick': '⚒',
    'hammer and wrench': '🛠',
    'dagger': '🗡',
    'crossed swords': '⚔',
    'water pistol': '🔫',
    'boomerang': '🪃',
    'shield': '🛡',
    'carpentry saw': '🪚',
    'wrench': '🔧',
    'screwdriver': '🪛',
    'nut and bolt': '🔩',
    'gear': '⚙',
    'clamp': '🗜',
    'balance scale': '⚖',
    'white cane': '🦯',
    'link': '🔗',
    'chains': '⛓',
    'hook': '🪝',
    'magnet': '🧲',
    'ladder': '🪜',
    'alembic': '⚗',
    'test tube': '🧪',
    'petri dish': '🧫',
    'dna': '🧬',
    'telescope': '🔭',
    'microscope': '🔬',
    'x-ray': '🩻',
    'adhesive bandage': '🩹',
    'pill': '💊',
    'syringe': '💉',
    'drop of blood': '🩸',
    'stethoscope': '🩺',
    'crutch': '🩼',

    // Home & misc
    'door': '🚪',
    'elevator': '🛗',
    'mirror': '🪞',
    'window': '🪟',
    'bed': '🛏',
    'couch and lamp': '🛋',
    'chair': '🪑',
    'toilet': '🚽',
    'plunger': '🪠',
    'shower': '🚿',
    'bathtub': '🛁',
    'mouse trap': '🪤',
    'razor': '🪒',
    'lotion bottle': '🧴',
    'safety pin': '🧷',
    'broom': '🧹',
    'basket': '🧺',
    'roll of paper': '🧻',
    'soap': '🧼',
    'toothbrush': '🪥',
    'sponge': '🧽',
    'fire extinguisher': '🧯',
    'shopping cart': '🛒',
    'bucket': '🪣',
    'cigarette': '🚬',
    'coffin': '⚰',
    'headstone': '🪦',
    'funeral urn': '⚱',
    'moai': '🗿',
    'placard': '🪧',
    'identification card': '🪪',

    // Symbols / signs
    'ATM sign': '🏧',
    'litter in bin sign': '🚮',
    'potable water': '🚰',
    'wheelchair symbol': '♿',
    'mens room': '🚹',
    'womens room': '🚺',
    'restroom': '🚻',
    'baby symbol': '🚼',
    'water closet': '🚾',
    'passport control': '🛂',
    'customs': '🛃',
    'baggage claim': '🛄',
    'left luggage': '🛅',
    'warning': '⚠',
    'children crossing': '🚸',
    'no entry': '⛔',
    'prohibited': '🚫',
    'no bicycles': '🚳',
    'no smoking': '🚭',
    'no littering': '🚯',
    'non-potable water': '🚱',
    'no pedestrians': '🚷',
    'no mobile phones': '📵',
    'no one under eighteen': '🔞',
    'radioactive': '☢',
    'biohazard': '☣',
    'up arrow': '⬆',
    'up-right arrow': '↗',
    'right arrow': '➡',
    'down-right arrow': '↘',
    'down arrow': '⬇',
    'down-left arrow': '↙',
    'left arrow': '⬅',
    'up-left arrow': '↖',
    'up-down arrow': '↕',
    'left-right arrow': '↔',
    'right arrow curving left': '↩',
    'left arrow curving right': '↪',
    'right arrow curving up': '⤴',
    'right arrow curving down': '⤵',
    'clockwise vertical arrows': '🔃',
    'counterclockwise arrows button': '🔄',
    'BACK arrow': '🔙',
    'END arrow': '🔚',
    'ON! arrow': '🔛',
    'SOON arrow': '🔜',
    'TOP arrow': '🔝',
    'place of worship': '🛐',
    'atom symbol': '⚛',
    'om': '🕉',
    'star of david': '✡',
    'wheel of dharma': '☸',
    'khanda': '🪯',
    'yin yang': '☯',
    'orthodox cross': '☦',
    'ophiuchus': '⛎',
    'aries': '♈',
    'taurus': '♉',
    'gemini': '♊',
    'cancer': '♋',
    'leo': '♌',
    'virgo': '♍',
    'libra': '♎',
    'scorpio': '♏',
    'sagittarius': '♐',
    'capricorn': '♑',
    'aquarius': '♒',
    'pisces': '♓',
    'check mark': '✔',
    'check box with check': '☑',
    'check mark button': '✅',
    'cross mark': '❌',
    'cross mark button': '❎',
    'plus': '➕',
    'minus': '➖',
    'divide': '➗',
    'multiply': '✖',
    'heavy equals sign': '🟰',
    'infinity': '♾',
    'double exclamation mark': '‼',
    'exclamation question mark': '⁉',
    'red question mark': '❓',
    'white question mark': '❔',
    'white exclamation mark': '❕',
    'red exclamation mark': '❗',
    'wavy dash': '〰',
    'currency exchange': '💱',
    'heavy dollar sign': '💲',
    'medical symbol': '⚕',
    'recycling symbol': '♻',
    'fleur-de-lis': '⚜',
    'trident emblem': '🔱',
    'name badge': '📛',
    'japanese symbol for beginner': '🔰',
    'hollow red circle': '⭕',
    'curly loop': '➰',
    'double curly loop': '➿',
    'part alternation mark': '〽',
    'eight-spoked asterisk': '✳',
    'eight-pointed star': '✴',
    'sparkle': '❇',
    'copyright': '©',
    'registered': '®',
    'trade mark': '™',
    'red circle': '🔴',
    'orange circle': '🟠',
    'yellow circle': '🟡',
    'green circle': '🟢',
    'blue circle': '🔵',
    'purple circle': '🟣',
    'brown circle': '🟤',
    'black circle': '⚫',
    'white circle': '⚪',
    'red square': '🟥',
    'orange square': '🟧',
    'yellow square': '🟨',
    'green square': '🟩',
    'blue square': '🟦',
    'purple square': '🟪',
    'brown square': '🟫',
    'black large square': '⬛',
    'white large square': '⬜',
    'large orange diamond': '🔶',
    'large blue diamond': '🔷',
    'small orange diamond': '🔸',
    'small blue diamond': '🔹',
    'red triangle pointed up': '🔺',
    'red triangle pointed down': '🔻',
    'diamond with a dot': '💠',
    'radio button': '🔘',
    'white square button': '🔳',
    'black square button': '🔲',

    // Flags
    'chequered flag': '🏁',
    'triangular flag': '🚩',
    'crossed flags': '🎌',
    'black flag': '🏴',
    'white flag': '🏳',
    'rainbow flag': '🏳️‍🌈',
    'transgender flag': '🏳️‍⚧️',
    'pirate flag': '🏴‍☠️',
    'flag Italy': '🇮🇹',
    'flag United Kingdom': '🇬🇧',
    'flag United States': '🇺🇸',
    'flag France': '🇫🇷',
    'flag Germany': '🇩🇪',
    'flag Spain': '🇪🇸',
    'flag Japan': '🇯🇵',
    'flag China': '🇨🇳',
    'flag Brazil': '🇧🇷',
    'flag Canada': '🇨🇦',
    'flag Australia': '🇦🇺',
    'flag European Union': '🇪🇺',
  };

export const DECK_EMOJI_LABELS = LABELS;
